### ISSUE TITLE
Update query turns Mongoose Long to Timestamp(0,0) in database

### ISSUE THREAD

**Issue by shubsaini09** [aheckmann/mongoose-long#4]
// this is how my schema is defined
require('mongoose-long')(Mongoose);
var SchemaTypes = Mongoose.Schema.Types;
var schema = new Mongoose.Schema({
SecretNumber: { type: SchemaTypes.Long, min: 0, default: 0}
});
// update query
Test.statics.updateData = function(data, callback) { 
    console.log(data.SecretNumber); // return the number
    this.update({CaID:data.CaID},
        {$set:
            {
                 SecretNumber:data.SecretNumber,
            }
        },callback);
};
After updating the data when i check in the database, result is 
{ "_id" : ObjectId("565a07b5c1c80e6ee05cc326"), "SecretNumber" : Timestamp(0, 0) }

Note: I am facing this problem only in update query while it works fine when i am trying to insert data.

**Comment by vkarpov15** [comment]
Might be related to https://github.com/Automattic/mongoose/issues/4283 . The fix for that will be in mongoose 4.5.4, can you try again once that's released?

**Comment by shubsaini09** [comment]
Okay

**Comment by vkarpov15** [comment]
4.5.4 was released a couple days ago, let me know if it works :+1:

**Comment by shubsaini09** [comment]
It works fine now :)

**Comment by vkarpov15** [comment]
:tada:
